### ISSUE TITLE
examples/helloworld_tx/helloworld_tx.pde - Compilation Error

### ISSUE THREAD

**Issue by emil01** [maniacbug/RF24Network#10]
Compiling gives the following error (it applies for both the rx&tx example):

E:\Apps\arduino-1.0.5\libraries\RF24Network\RF24Network.cpp: In member function 'void RF24Network::begin(uint8_t, uint16_t)':
E:\Apps\arduino-1.0.5\libraries\RF24Network\RF24Network.cpp:33: error: 'class RF24' has no member named 'isValid'
E:\Apps\arduino-1.0.5\libraries\RF24Network\RF24Network.cpp: In member function 'void RF24Network::update()':
E:\Apps\arduino-1.0.5\libraries\RF24Network\RF24Network.cpp:60: error: 'class RF24' has no member named 'isValid'

**Comment by emil01** [comment]
i deleted the references from the RF24Network.cpp and it is working fine now. But is this the right way to go about?

**Comment by DevGW** [comment]
I'm getting the same error and was just about to delete the reference as well ... did this work out well for you emil01?

**Comment by emil01** [comment]
I installed the updated libraries and then it worked fine for me

**Comment by 1swe23** [comment]
Hello i'm newbie with Nrf24l01+ module.I'm also getting the same error. i have also deleted the references from the RF24Network.cpp file, then also same error is there.Please suggest if some other changes need to be done

**Comment by emil01** [comment]
Have you tried using the latest libraries?

**Comment by 1swe23** [comment]
thanks for replying.can u please share the link for the new libraries. I am unable to find the new libraries. thanks in advance.

**Comment by emil01** [comment]
Download from here:

https://github.com/maniacbug/RF24Network?files=1

Don't remember if it has been updated since I last used it, check it out
and confirm if it works, else I will try and figure this out once I am
home.
