### ISSUE TITLE
Wifi and rf24?

### ISSUE THREAD

**Issue by Skeyelab** [maniacbug/RF24Network#14]
Can one arduino use a wifi shield and a rf24 at the same time? If like to make my node 0 have wifi.

**Comment by ramonlh** [comment]
Why not? You must be careful with the frequencies and channels.
I' using use the node 0 and Arduino Mega2560+Ethernet Shield+TPLink MR3020 in the same box.

**Comment by Skeyelab** [comment]
Thanks. It seemed that the rf24 and wifi shield use the same pins to communicate. 

Eric Dahl

**Comment by ramonlh** [comment]
Eric,

The wifi shield and then Ethernet shield use pins 11,12 and 13 (50,51 
and 52 on the Mega). Also pin 10 for Select.

NRF24L01 uses 8 for Select and 9 for CE (ex.)

Ramón

**Comment by Skeyelab** [comment]
OK, I must be missing something here.  according to your blog post, the
NRF24L01 is also using pins 9,10,11,12,13

can both the wifi shield and NRF share 11,12 & 13?

http://maniacbug.wordpress.com/2011/11/02/getting-started-rf24/

## 

Eric Dahl
Head Engineer
Skeyelab Music
eric@skeyelab.com

www.skeyelab.com

"I don't even know how to set up an email signature." Jeremy Goodman

**Comment by ramonlh** [comment]
Yes,

Pin 10 selects Ethernet/Wifi shield.
Pin 8 selects NRF24L01 module, pin 9 enables module. (8-9 in my sketch, 
you can modify it)
11,12 and 13 are commons.

Ramón

**Comment by Skeyelab** [comment]
Awesome!  Thanks!

**Comment by ramonlh** [comment]
See this image: http://commons.wikimedia.org/wiki/File:SPI_three_slaves.svg

**Comment by ramonlh** [comment]
Eric,
this is my prototype with Ethernet shield + NRF24L01.  It's running at 
http://elconucom.dyndns.org:82.

Saludos
Ramón
