### ISSUE TITLE
HelloWord_rx Example compilation error

### ISSUE THREAD

**Issue by MauroHKT** [maniacbug/RF24Network#17]
Hi, I just tried to upload this sketch but I get following error message:

/Users/MaoHKT/Documents/Arduino/libraries/RF24Network/RF24Network.cpp: In member function 'void RF24Network::update()':
/Users/MaoHKT/Documents/Arduino/libraries/RF24Network/RF24Network.cpp:67: error: void value not ignored as it ought to be

I don't know what to do.... anyone else has same problem ?

**Comment by heinemml** [comment]
Hm, looks like you have a version of the RF24 Library that is not working with RF24Network. 

The read() Function of your RF24-Library returns void but should return bool (like [here](https://github.com/maniacbug/RF24/blob/master/RF24.h#L304)).

Do you use the latest one from https://github.com/maniacbug/RF24 ?

**Comment by MauroHKT** [comment]
Thank's for your advice, I will try to download the new ver of the RF24 Lib from your link and I'll let you know asap if it works.
have a great day
Mauro

**Comment by MauroHKT** [comment]
Thank's once again. now with the new fork of RF24 it compile w/o error.

**Comment by heinemml** [comment]
Happy to help!

**Comment by bloukingfisher** [comment]
Thanks, downloading and re-installing the library fixed the same problem for me. I was skeptical since the rest of the RF24 functionality seemed to work fine, but this was the fix!
