### ISSUE TITLE
RF24Network and TVOut library

### ISSUE THREAD

**Issue by Avamander** [maniacbug/RF24Network#20]
I am using the example DemoNTSC sketch of TVOut library but as soon as I add this line

RF24Network network(radio);

the TVOut library breaks somehow. What could be the cause and is there a way I could fix it?

**Comment by MauroHKT** [comment]
post your code

**Comment by Avamander** [comment]
That is unneccesary. I only added three lines to the sketch (DemoNTSC that works without the third added line)

1) nrf24l01+ pin configuration

2) RF24 

3) RF24Network network(radio);
